### ISSUE TITLE
Merge mergeable AIR constraints

### ISSUE THREAD

**Issue by aszepieniec** [TritonVM/triton-vm#1]
Naïvely, you compute one quotient polynomial for every AIR constraint. However, if the support (= points where the composition polynomials evaluate to zero) is the same, then it pays to combine the AIR polynomials using random verifier-supplied coefficients first. Then compute fewer quotient polynomials. This speeds up both prover and verifier computations.
Specifically, the mergeable AIR constraints are:
 - all boundary constraints (since they all pertain to row 0 in their respective tables)
 - all transition constraints but separately for each table (unless the tables happen to share the same omicron)
 - all terminal constraints but separately for each table (ditto)

**Comment by jan-ferdinand** [comment]
Paraphrasing @aszepieniec, this is (1) a marginal improvement that's (2) short-lived because we're moving away from expressing the AIR as polynomials once the VM's specification is considered final and (3) prone to introduce errors, which might become attack vectors.
