### ISSUE TITLE
Interactive, graphical, stepping debugger

### ISSUE THREAD

**Issue by sshine** [TritonVM/triton-vm#105]
For debugging large programs written in TritonVM it is possible to run the VM setting a breakpoint in `.step()`.

This does not render the `VMState` in a particularly pretty way, since it's just a rather large struct in memory.

Using [CodeLLDB in VSCode](https://github.com/vadimcn/vscode-lldb/#screenshots), it is possible to apply data visualisation to debugging.

We should be able to visualise a `VMState` by making a similar drawing, importing the visualiser when initialising the debugger, and setting a conditional breakpoint with an expression that renders graphically. There is a [tutorial](https://github.com/vadimcn/vscode-lldb/wiki/Data-visualization) that uses Python and `matplotlib` to draw a Mandelbrot set being generated by a piece of C++ code. Our case should be even simpler, but we may need some cool graphics to make the visualiser seem like TritonVM is a retro architecture.

**Comment by jan-ferdinand** [comment]
superseded by #242
