### ISSUE TITLE
Revisit Swap

### ISSUE THREAD

**Issue by aszepieniec** [TritonVM/triton-vm#110]
The current arithmetization of `swap` is very expensive. It requires 48 (!) polynomials, most of which are of high degree.

This issue is about studying the costs and benefits of alternatives, and implement them if the latter are determined to outweigh the former.

Here is one alternative: restrict the argument to a) odd numbers or b) powers of two, and simulate the other swaps via pseudoinstructions.

**Comment by jan-ferdinand** [comment]
Commits 3e96facad157aba2f1794a7b73dd9b3a353298a2 and 62187169ad1fd55221eef7a752f7ee81c87d1d34 alleviate the problem by reducing the number of constraints (outside of constraint groups) to 1, which is of degree 5. The constraints defined by constraint groups number 14, of which 4 are of degree 2 and 8 are of degree 1.
