### ISSUE TITLE
Scope-Level Abstraction Language

### ISSUE THREAD

**Issue by aszepieniec** [TritonVM/triton-vm#112]
Writing programs in Triton Assembler is hard because of the bookkeeping the programmer needs to do to keep the jump stack in order. For instance, [there is a solution for if-then-else](https://github.com/TritonVM/triton-vm/pull/84#issuecomment-1277379425) but it introduces wrapper code blocks for each branch to take care of the bookkeeping.

I suggest adding a new layer of abstraction, higher than pseudo-instructions, that allows the programmer to write something like this:

```
if // implicitly test st0 =/= 0
{
  // if-branch
} else {
  // else-branch
}
```

The compiler parses code in this scope-level format and then auto-generates the pseudo-instructions. The compiler should be able to handle nested scopes.

Question: what other scope-level constructions do we want to abstract out? E.g., `while` comes to mind.

**Comment by jan-ferdinand** [comment]
[The repository currently named “TASM lang”](https://github.com/TritonVM/tasm-lang) solves this issue for the time being.
