### ISSUE TITLE
use arithmetic circuits to their full potential

### ISSUE THREAD

**Issue by jan-ferdinand** [TritonVM/triton-vm#115]
From [#106](https://github.com/TritonVM/triton-vm/pull/106#pullrequestreview-1176367953):

- [x] #96
- [x] #123
- [ ] phase out multivariate polynomials entirely
- [ ] generate a function that can compute the partially evaluated circuits quickly
- [ ] apply that function to compute quotients
- [ ] generate optimal
	- [x] rust code
	- [ ] TASM
	- [ ] etc. code

**Comment by Sword-Smith** [comment]
Functionality to compute degrees and symbolic degree bounds was included in 20a8e7c946285c34a8484723345886a36a1811bf. But it's not being used yet.

**Comment by jan-ferdinand** [comment]
The remaining tasks of this issue are considered outdated or will be made into their own issues.
