### ISSUE TITLE
distinguish AIR constraints for base tables and extension tables

### ISSUE THREAD

**Issue by jan-ferdinand** [TritonVM/triton-vm#119]
Multiplying two `XFieldElement`s requires 12 multiplications of `BFieldElement`s. AIR constraints that only pertain to a table's base columns do not need to have type `XFieldElement`, but for reasons of convenience, they currently do.

Refactor the code, and possibly the involved traits such as `Evaluable`, to distinguish between constraints for the base table and constraints for the extension table.

**Comment by Sword-Smith** [comment]
After speaking to @bobbinth we realized that we could probably make this distinction on the leaf type for the `ConstraintCircuit` struct that we use to auto generate code for evaluating constraints. We should distinguish whether something is an `base_field_input` or an `extension_field_input`.

**Comment by jan-ferdinand** [comment]
As far as I know, joint credit also to @grjte. :relieved:

**Comment by jan-ferdinand** [comment]
It's probably best to wait until #139 is in place.
