### ISSUE TITLE
Avoid memory allocation inside busy-loops?

### ISSUE THREAD

**Issue by Sword-Smith** [TritonVM/triton-vm#122]
The autogenerated code for evaluating a transition codewords returns a vector for each element in the FRI domain. I wonder if the code wouldn't be faster if the entire data structure for holding the result (the transition quotient/transition codeword values) was generated outside the busy-loop (the loop that runs over the entire FRI domain) and the function that calculates a list of transition quotients/codewords for a single point then only got a mutable reference to a slice in the data structure that stores the result. 

My intuition tells me that allocations of vectors inside these busy loops slows the code down.

Current function signature
```rust
 #[inline]
fn evaluate_transition_constraints(
        &self,
        current_row: &[XFieldElement],
        next_row: &[XFieldElement],
        challenges: &AllChallenges,
    ) -> Vec<XFieldElement> {
```

Suggested function signature, returning void.
```rust
#[inline]
    fn evaluate_transition_constraints(
        &self,
        current_row: &[XFieldElement],
        next_row: &[XFieldElement],
        challenges: &AllChallenges,
        res: &mut [XFieldElement; CONSTRAINT_COUNT],
    )
```

`res` could be an array pointer or a pointer to a vector, or a mutable slice. Not sure what would type check and work best.

**Comment by jan-ferdinand** [comment]
Constraint evaluation is very fast now – closing.
