### ISSUE TITLE
Personalize Quotient Domain per Table

### ISSUE THREAD

**Issue by aszepieniec** [TritonVM/triton-vm#128]
Every table should have its own quotient domain. This way we can reduce the domain size (and hence number of rows over which the constraints are evaluated) for tables whose AIRs are not of the highest degree. This yields a non-trivial speedup.

**Comment by aszepieniec** [comment]
Here is an illustration why the speedup is both non-trivial and difficult to quantify. Currently, there is no point in reducing the AIR degree of the ProcessorTable below 9 because then the quotient domain is determined by the Hash Table (whose AIR degree remains 9). So even if we reduce the Processor's AIR degree to 5, we would still have to evaluate the constraints on a quotient domain of `(9-1)*padded_height`. But if we have a quotient domain that's specific to the Processor Table, then we can evaluate the Processor's constraints on a quotient domain of only `(5-1)*padded_height`, which is half the size.

**Comment by jan-ferdinand** [comment]
Once #139 is in place, we can go one step further and use the correct quotient-domain on a per-quotient basis.

**Comment by jan-ferdinand** [comment]
Going even one step further, the per-quotient personalized domain is the same for every quotient once #143 is in place, _i.e.,_ #143 supersedes this issue.
