### ISSUE TITLE
Repeated nodes identified in multiple tables

### ISSUE THREAD

**Issue by Sword-Smith** [TritonVM/triton-vm#142]
After talking to @andrewmilson and @bobbinth about the multicircuit design and the associated compiler to generate code for the evaluation of the constraints, I discovered that we have repeated nodes in our constraint multicircuits. That means that we have nodes that evaluate to the same value but are not seen as equal by the `Eq` implementation.

This is great news since it means we can speed up constraint evaluation even more than the 2000x we have already achieved.

The problem can be solved in multiple ways but the method I'm leaning towards is to run the test that catches this problem on all constraint definitions and then fix the problem where the constraints are defined, so in the respective tables.

An alternative is to use this new check in a new version of "constant folding" where repeated nodes are simply just removed/replaced with their equivalent counterpart without notifying the designer.

The test has only been run on transition constraints. The following four tables fail that test:
- jump stack table
- op stack table
- processor table
- ram stack table

The branch `identify-repeated-nodes` can be checked out and the tests under the namespace `constraint_circuit_tests` can be run to see the failing tests.

**Comment by Sword-Smith** [comment]
The branch `identify-repeated-nodes` contains a part of the solution. It solves the problem for jump stack, op stack, and RAM stack. Unfortunately I was struggling solving it for processor table.

**Comment by Sword-Smith** [comment]
It seems to me that the culprit is a combination of circuit construction and the constant folder. At one point a node of value 1 is made and that is combined as `1 +/- 0` at one point and this is then constant folded to another 1 which is then identified as the repeated node.

**Comment by Sword-Smith** [comment]
The branch `identify-repeated-nodes` will along with the test `cargo t constant_folding_processor_table_test -- --nocapture` give some good clues.

**Comment by jan-ferdinand** [comment]
Thanks for identifying and investigating more speedup potential! For now, I'm un-assigning myself from this issue since I'll be focused on #139 and #7 for a while.
