### ISSUE TITLE
Too many ways to run the VM

### ISSUE THREAD

**Issue by sshine** [TritonVM/triton-vm#150]
The task is to 

1. reduce the number of functions that will run Triton VM in various ways
2. put them in more logical places (their location is a bit random)

These `pub fn` are considered worth keeping:

- `Program`:
  - `::new(labelled_instructions)`
  - `::from_code(code: &str)`
  - `::from_file(path: &Path)`
  - `.simulate(stdin, secret_in)`
  - `.to_bwords()`
- `Stark`:
  - `::new(security_level, fri_expansion_factor)`
  - `::default()`
  - `.prove(aet, maybe_profiler)`
  - `.verify(proof, maybe_profiler)`
- ?:
  - something like `parse_simulate_prove`, but which doesn't live in shared_tests.

These `pub fn` are contenders for deletion:

- `shared_tests`:
  - `parse_simulate_prove(code, stdin, secret_in, maybe_profiler)`
  - `parse_setup_simulate(code, stdin, secret_in)`
- `SourceCodeAndInput`, `without_input`, `run`, `simulate`
- `Program`:
  - `simulate_no_input`
  - `run` (consequently `.step()`, since `.simulate()` uses only `.step_mut()`)
  - `.len()`
  - `.is_empty()`
- `Stark`:
  - `parse_setup_simulate`
  - `parse_simulate_pad`
  - `parse_simulate_pad_extend`

Upon deleting these, two gaps appear:

- Some tests only cover part of the pipeline. Cater to call sites that don't go all the way to `.prove()`.
- Composing `::from_code()`, `.simulate()`, `.prove()` and together in one exposed function.

**Comment by einar-triton** [comment]
I will have a look at this.

**Comment by einar-triton** [comment]
@sshine can you confirm that by `Program:` `.len()`, you refer to `len_bwords()`?

**Comment by jan-ferdinand** [comment]
I think we are in a decent state here for now. Most of the mentioned methods have changed or disappeared since this issue was opened. In case any oddity still jumps out, please open a new issue.
