### ISSUE TITLE
Barycentric Low-degree Verification for FRI

### ISSUE THREAD

**Issue by aszepieniec** [TritonVM/triton-vm#156]
The last codeword sent in FRI has to be of low degree. What's the best way to prove this? The Miden team proposes [this](https://github.com/0xPolygonMiden/miden-vm/issues/568):
 - send both the codeword `[q_i | 0 <= i < m]` and the polynomial `P(X)` that corresponds to it (but don't send the coefficients known to be zero)
 - pick a random `τ`
 - evaluate `P(X)` in `τ` using straightforward Horner evaluation
 - evaluate the interpolant through `[q_i | 0 <= i < m]` in `τ` using the [Barycentric Lagrange formula](https://people.maths.ox.ac.uk/trefethen/barycentric.pdf). This step requires $O(m^2)$ precomputation work and $O(m)$ online work.
 - Equate the two evaluations.

The soundness error is bounded by `m / |F|`, where `|F|` is the size of the field from which `τ` is drawn.

**Comment by jan-ferdinand** [comment]
See #5 for the different (possibly prohibitively expensive) answer to the same question.
