### ISSUE TITLE
Make Triton VM easy to run

### ISSUE THREAD

**Issue by sshine** [TritonVM/triton-vm#164]
It should be easy to run Triton VM. It's not so easy right now, and there aren't instructions.

There are two scenarios:

- Import Triton VM in a Rust project, e.g. for benchmarking. Inclusion in [zkp-compiler-shootout](https://github.com/anoma/zkp-compiler-shootout/) is one goal. The success criterion: It should be possible to import `triton-vm` as a dependency and use one easy to guess constructor for running the VM (`*cough*` #150 `*cough*`) by feeding it a program in the form of a `&str` and field elements in the form of `u64`s.
- Run Triton VM as a command-line tool; Andrew Milson's [demo of ministark](https://github.com/andrewmilson/ministark#demo---proving-brainfk-programs) is a good example; basically one sub-command for proving and dumping something into a file (or stdout), and another sub-command for verifying by reading that file (or stdin).

**Comment by jan-ferdinand** [comment]
- The first point is addressed by the resolution of #150, updated and improved [documentation](https://docs.rs/triton-vm/latest/triton_vm/), and the [scaffold repository](https://github.com/TritonVM/triton-vm-scaffold/blob/main/src/main.rs).
- The second point is extracted into #238.
