### ISSUE TITLE
More repeated instructions

### ISSUE THREAD

**Issue by Sword-Smith** [TritonVM/triton-vm#222]
Can we expand this list? There are many instructions, for which I would like this convenient syntax

```rust
    // repeated instructions
    [push $arg:literal; $num:expr] => { vec![ $crate::triton_instr!(push $arg); $num ] };
    [dup $arg:literal; $num:expr] => { vec![ $crate::triton_instr!(dup $arg); $num ] };
    [swap $arg:literal; $num:expr] => { vec![ $crate::triton_instr!(swap $arg); $num ] };
    [call $arg:ident; $num:expr] => { vec![ $crate::triton_instr!(call $arg); $num ] };
    [$instr:ident; $num:expr] => { vec![ $crate::triton_instr!($instr); $num ] };
```

I would like it for `read_io`, `write_io`, `divine`, and, if possible, also for `dup {n}` where `n` is not known at compile-time.

**Comment by jan-ferdinand** [comment]
The last line you pasted above, namely

```rust
[$instr:ident; $num:expr] => { vec![ $crate::triton_instr!($instr); $num ] };
```

captures all instructions not explicitly listed. Therefore, all instructions should work with the `triton_asm![instruction; num]` syntax.

> if possible, also for `dup {n}` where `n` is not known at compile-time

Anything implementing a sane `Display` should be accepted by the macros. A

```rust
let dup_arg = 3;
let instructions = triton_asm!(dup {dup_arg});
```

should be totally fine – see also the documentation of the `triton_program!` macro for further examples.

Did you encounter problems with either of the features?
