### ISSUE TITLE
`payload_type`  does not evaluate its constants

### ISSUE THREAD

**Issue by Sword-Smith** [TritonVM/triton-vm#249]
```rust
ProofItemVariant::OutOfDomainQuotientSegments.payload_type()
```

returns the string `[XFieldElement; NUM_QUOTIENT_SEGMENTS]` instead of `[XFieldElement; 4]`. Would it be possible to return the value of constants instead of the names of the constants?

**Comment by Sword-Smith** [comment]
And the `NUM_QUOTIENT_SEGMENTS` constant is private to this repo, so I can't get its value from here :)

**Comment by jan-ferdinand** [comment]
Quick workaround: `TARGET_AIR_DEGREE` is always the same value, but of a different type. I'll look at this again to do it properly. :+1:

**Comment by Sword-Smith** [comment]
> The constant `NUM_QUOTIENT_SEGMENTS` is public as of Triton VM v0.37.0. Does that solve the issue?

Yes :)
