### ISSUE TITLE
Can the `bfe!`/`xfe!` macros produce `const` values?

### ISSUE THREAD

**Issue by Sword-Smith** [TritonVM/triton-vm#260]
Would be convenient for this code: 

```rust
pub const FIRST_PROOF_ITEM_ELEMENT_POINTER: BFieldElement = BFieldElement::new(2);
```

**Comment by jan-ferdinand** [comment]
This issue belongs firmly in [`twenty-first`](https://github.com/Neptune-Crypto/twenty-first). :blush:

**Comment by jan-ferdinand** [comment]
That said: what's wrong with calling `BFieldElement::new`?
