### ISSUE TITLE
Last FRI polynomial is not normalized

### ISSUE THREAD

**Issue by Sword-Smith** [TritonVM/triton-vm#268]
The last FRI polynomial is not added to the proof stream in a normalized manner, making the degree-check (in Triton VM/TASM) of the last round harder than it should be. Currently, we do:

```rust
    fn send_last_polynomial(&mut self) {
        let last_codeword = &self.rounds.last().unwrap().codeword;
        let last_polynomial = ArithmeticDomain::of_length(last_codeword.len())
            .unwrap()
            .interpolate(last_codeword);
        let proof_item = ProofItem::FriPolynomial(last_polynomial.coefficients);
        self.proof_stream.enqueue(proof_item);
    }
```

Which adds a list of coefficients to the proof stream which will have trailing zeros. A potential solution is to change the above-function to:

```rust
    fn send_last_polynomial(&mut self) {
        let last_codeword = &self.rounds.last().unwrap().codeword;
        let mut last_polynomial = ArithmeticDomain::of_length(last_codeword.len())
            .unwrap()
            .interpolate(last_codeword);
        last_polynomial.normalize();
        let proof_item = ProofItem::FriPolynomial(last_polynomial.coefficients);
        self.proof_stream.enqueue(proof_item);
    }
```

This, combined with a test that the last polynomial is always shared in its normalized form, should solve the problem. The alternative is to write a degree-checker in Triton VM assembly but that seems needlessly complicated and will also lead to larger-than-necessary proofs.

**Comment by jan-ferdinand** [comment]
How about adding `BFieldCodec` support for `Polynomial` instead? That seems like the more general approach to me.

**Comment by Sword-Smith** [comment]
Superseeded by 1979ef12b9d450f8f1a19a36796d0f1748aef752
