### ISSUE TITLE
Drop Duplicate Consts

### ISSUE THREAD

**Issue by aszepieniec** [TritonVM/triton-vm#298]
The `*BaseTableColumn` and `*ExtTableColumn` structs define *two* consts indicating the number of columns: `BASE_WIDTH` (respectively `EXT_WIDTH`) and `COUNT`. The latter one is automatically derived via strum.

Having multiple `const`s referring to the same value is prone to error.

- [ ] refactor: Drop duplicate width indicator from column structs

**Comment by jan-ferdinand** [comment]
Completed as of f594167d803d0b4fad0be95507bca329bad54cef.
