### ISSUE TITLE
subtraction/negation opcode

### ISSUE THREAD

**Issue by vimwitch** [TritonVM/triton-vm#306]
Hi, really like the work here.

I'm writing a simple compiler and noticed there is no subtraction/negation operator. I'm thinking of doing the following:
```
// doing 5 - 3
push 5
push 3
push 18446744069414584320
mul
add
```

This isn't ideal for a couple reasons:
- consumes space on the stack
- `18446744069414584320` is not guaranteed to be -1 if we're executing in a different field

Are there any plans to add a negation operator, or is there a more efficient recommended approach?

**Comment by vimwitch** [comment]
I just realized i can write `push -1`. This doesn't solve the stack use issue, but is good enough for me to close this.

**Comment by Sword-Smith** [comment]
Be sure to check out the [standard library](https://github.com/TritonVM/tasm-lib), we developed. There's a lot of support for `u32`, `u64`, and even `u128` there, among other things.
