### ISSUE TITLE
Memory opcode stack layout is incorrect

### ISSUE THREAD

**Issue by vimwitch** [TritonVM/triton-vm#308]
In the docs here `write_mem` instruction specifies that the memory pointer is at the end of elements being written.

<img width="375" alt="Screenshot 2024-07-18 at 00 06 22" src="https://github.com/user-attachments/assets/4af2d23d-5de5-4fca-bd53-0184d71f7a3c">

In reality I'm seeing the pointer value being pulled from the top of the stack. e.g. to insert a value `111` and `222` at memory index 3:
```asm
push 111
push 222
push 3
write_mem 2
```

the resulting stack is `5` in the current implementation

from reading the docs i would expect the correct logic to be
```asm
push 3
push 111
push 222
write_mem 2
```

but in the current implementation the stack is `224`

**Comment by aszepieniec** [comment]
I agree that the stack should be `_ 3`. You are saying that the stack is empty. Am I understanding that correctly? Is this a minimal working example I can use to start hunting down this discrepancy, or is there more context that makes your counterexample work?

**Comment by vimwitch** [comment]
Sorry a description with a single element was not a replica. The examples above replicate the difference.

My understanding of `_ b a p` is that `_` is the top of the stack, is this correct?

**Comment by aszepieniec** [comment]
No, it's the other way around: `_` is the bottom of the stack.

**Comment by vimwitch** [comment]
ok, thanks!

**Comment by Sword-Smith** [comment]
Let's go through your code and show what the stack looks like after each instruction

```tasm
// _

push 111
// _ 111

push 222
// _ 111 222

push 3
// _ 111 222 3

write_mem 2
// _ 5

```

**Comment by vimwitch** [comment]
it's a bit counter-intuitive (IMO) because the tui looks like this:

<img width="375" alt="image" src="https://github.com/user-attachments/assets/acaf6c24-11a4-4d91-97a6-6a50802cf1d3">

So I assumed it was top-down in the docs as well, with the `_` implied as the top

**Comment by Sword-Smith** [comment]
I think something's wrong with this picture. `_ 111 222 3` means stack element `0` has value `3`, stack element `1` has value `222`, and stack element `2` has value `111`.

**Comment by vimwitch** [comment]
i was using this example in that image

```asm
push 3
push 111
push 222
write_mem 2
```
