### ISSUE TITLE
Update spec to reflect digest length (6 → 5) change

### ISSUE THREAD

**Issue by sshine** [TritonVM/triton-vm#60]
- [ ] In [isa.md](https://github.com/TritonVM/triton-vm/blob/master/specification/isa.md): Occurrences of "6" and "12".
- [ ] In [arithmetization.md](https://github.com/TritonVM/triton-vm/blob/master/specification/arithmetization.md): Constraint polynomials.

The changes must reflect changes made to the source code.

The source code currently depends on `twenty-first-0.1`.

The digest length (6 → 5) change lives in `twenty-first-0.2`.

**Comment by aszepieniec** [comment]
These issues are solved in part (or in whole?) by commit [#6b8814b](https://github.com/TritonVM/triton-vm/pull/59/commits/6b8814b1dd1de93962153f0688aee85c8f0c7252) of PR [59](https://github.com/TritonVM/triton-vm/pull/59).
