### ISSUE TITLE
Derive number of challenges programmatically

### ISSUE THREAD

**Issue by aszepieniec** [TritonVM/triton-vm#90]
Currently, the number of challenges is hardcoded in `challenges.rs`, near the top:

```
impl AllChallenges {
    pub const TOTAL_CHALLENGES: usize = 130;
    ....
}
```

All challenges have a specific distinct purpose and are named. So it should be possible to derive the total number programmatically.

**Comment by jan-ferdinand** [comment]
One possibility is to use a macro like [field_count](https://crates.io/crates/field_count). Better options might exist.
