### ISSUE TITLE
Implement Transition Constraints for Correct Updating of Extension Columns for Cross-Table Arguments

### ISSUE THREAD

**Issue by aszepieniec** [TritonVM/triton-vm#91]
Cross-table arguments like Evaluation Arguments and Permutation Arguments need an extension column on both tables to compute a running evaluation or running product. This correct computation is not verified, to the best of my knowledge. This task involves writing transition constraints in all tables to verify the correct updates to these columns.

**Comment by jan-ferdinand** [comment]
See also #20
